### ISSUE TITLE
home-assistant.log - Error while setting up noaa_tides platform for sensor

### ISSUE THREAD

**Issue by christopherdopp** [jshufro/home_assistant_noaa_tides#10]
I recently discovered your enhanced version of noaa_tides and really enjoy the features you added. I am running home assistant 0.113.0 and noticed the following error in my home-assistant.log file:

```
2020-07-27 12:23:21 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up noaa_tides platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/noaa_tides/sensor.py", line 72, in setup_platform
    noaa_sensor.update()
  File "/config/custom_components/noaa_tides/sensor.py", line 335, in update
    _LOGGER.error("Received HTTP code %i from %s query", (r.status_code, self._station_url))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 180, in emit
    entry = LogEntry(
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 97, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not tuple
```

As far as I can tell, the component is working properly.

**Comment by jshufro** [comment]
Salient portion here is `_LOGGER.error("Received HTTP code %i from %s query", (r.status_code, self._station_url))` with `TypeError: %i format: a number is required, not tuple`.

I'll switch that over to an f-String to simplify things, but the reason I made this mistake is my entrenched C programmer printf habits.
