### ISSUE TITLE
NOAA Tiles

### ISSUE THREAD

**Issue by jkseamons** [jshufro/home_assistant_noaa_tides#23]
I am getting the following error with 2023.3.0 and newer

Logger: homeassistant.components.sensor
Source: custom_components/noaa_tides/sensor.py:63
Integration: Sensor (documentation, issues)
First occurred: 7:08:28 PM (2 occurrences)
Last logged: 7:08:28 PM

Error while setting up noaa_tides platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/noaa_tides/sensor.py", line 63, in async_setup_platform
    elif hass.config.units.is_metric:
AttributeError: 'UnitSystem' object has no attribute 'is_metric'

**Comment by jkseamons** [comment]
Updating to the latest version resolved issue
