### ISSUE TITLE
NOAA tides now broken

### ISSUE THREAD

**Issue by bschatzow** [jshufro/home_assistant_noaa_tides#32]
2025-1 is now in beta.  The custom integration changed from a warning to being now broken.

**Comment by jkosharek** [comment]
2025-1 is release and this is NOAA is now broken

**Comment by christopherdopp** [comment]
I upgraded to 2025-1 and have the following errors in my home-assistant.log file:

> 2025-01-03 20:54:58.928 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.noaa_tides.sensor',) in /usr/src/homeassistant/homeassistant/loader.py, line 1304: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")

2025-01-03 20:54:58.937 ERROR (MainThread) [homeassistant.config] Platform error: sensor - cannot import name 'DEVICE_CLASS_TEMPERATURE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1203, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'DEVICE_CLASS_TEMPERATURE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2025-01-03 20:54:58.938 ERROR (MainThread) [homeassistant.config] Platform error: sensor - cannot import name 'DEVICE_CLASS_TEMPERATURE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1203, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'DEVICE_CLASS_TEMPERATURE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2025-01-03 20:54:58.938 ERROR (MainThread) [homeassistant.config] Platform error: sensor - cannot import name 'DEVICE_CLASS_TEMPERATURE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1203, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'DEVICE_CLASS_TEMPERATURE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2025-01-03 20:54:59.167 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: list object has no element 0 when rendering '{{ value_json.species[0].commonName }}'
2025-01-03 20:55:01.154 ERROR (MainThread) [homeassistant.components.notify] Error setting up platform file
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 112, in async_setup_platform
    raise HomeAssistantError("Invalid notify platform.")  # noqa: TRY301
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant.exceptions.HomeAssistantError: Invalid notify platform.

**Comment by FortranFour** [comment]
Thank you, Flight-Lab, for your fix, which corrected some things. However, I am still receiving errors for the **buoy** and **water temperature** sensors.

**buoy:**

`Error adding entity sensor.buoy for domain sensor with platform noaa_tides
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1101, in __async_calculate_state
    original_device_class = self.device_class
                            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/noaa_tides/sensor.py", line 327, in device_class
    return SensorDeviceClass.TEMPERATURE
           ^^^^^^^^^^^^^^^^^
NameError: name 'SensorDeviceClass' is not defined
`

**water temperature:**

`Error adding entity sensor.water_temp for domain sensor with platform noaa_tides
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1101, in __async_calculate_state
    original_device_class = self.device_class
                            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/noaa_tides/sensor.py", line 241, in device_class
    return SensorDeviceClass.TEMPERATURE
           ^^^^^^^^^^^^^^^^^
NameError: name 'SensorDeviceClass' is not defined`

**Comment by FortranFour** [comment]
> @FortranFour I made an additional commit to that PR with a fix. Check it out and let me know how it works for you.

Perfect! Working again. You have my eternal gratitude!

**Comment by christopherdopp** [comment]
With the code changes @Flight-Lab made in [this pull request], (https://github.com/jshufro/home_assistant_noaa_tides/pull/33) the integration is working properly again with the latest home assistant version. 

Hopefully @jshufro will be able to merge the PR and create a new release version.

**Comment by jshufro** [comment]
Merged and tagged, thanks for the ping

https://github.com/jshufro/home_assistant_noaa_tides/releases/tag/0.2.0
